language: python

cache: pip
sudo: false

python:
    - 3.6
    - 3.7

before_install:
    - pip install -U setuptools pip
    - pip install -U pytest pytest-cov pytest-benchmark codecov

install:
    - pip install -U python-libsbml-experimental lxml
    - pip install -e .

script:
    - py.test --benchmark-skip --cov=micom

after_success:
    - codecov

notifications:
    email: false
