language: python
sudo: false

python:
    - 3.6
    - 3.7

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
    - conda activate test-environment
    - conda install numpy scipy pip
    - conda install -c ibmdecisionoptimization cplex
    - pip install pytest pytest-cov pytest-benchmark codecov

install:
    - pip install python-libsbml-experimental
    - pip install -e .

script:
    - py.test --benchmark-skip --cov=micom

after_success:
    - codecov

notifications:
    email: false
