language: python
sudo: false

python:
    - 3.6
    - 3.7

cache: pip

before_install:
    - pip install pytest pytest-cov pytest-benchmark codecov

install:
    - pip install cplex symengine python-libsbml-experimental
    - pip install -e .

script:
    - py.test --benchmark-skip --cov=micom

after_success:
    - codecov

notifications:
    email: false
