environment:

  global:
    PIP_CACHE_DIR: "pip_cache"

  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
    - PYTHON: "C:\\Miniconda37-x64"

matrix:
  fast_finish: true

cache:
  - '%LOCALAPPDATA%\pip\Cache'

platform: x64

build: off

install:
  # We need wheel installed to build wheels
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PYTHON%\Library\bin;%PATH%
  - set CONDA_ALWAYS_YES=true
  - "ECHO %PYTHON%"
  - python --version
  - python -m pip install -U pip
  - python -m pip install wheel pytest pytest-benchmark
  - conda install -c ibmdecisionoptimization cplex
  - python -m pip install .

test_script:
  - py.test --benchmark-skip
