name: Build and release docs

on:
  push:
    branches: [ master ]
 #   tags:
 #   - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pandoc
      run: |
        sudo apt-get -y install pandoc
    - name: Set up Python
      with:
        python-version: '3.8'
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip cryptography
        pip install wheel numpy Cython
        pip install biom-format
        pip install -e .
        pip install sphinx nbsphinx sphinx-book-theme
    - name: Build docs
      run: |
        cd docs && make html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
