name: Python package

on:
  push:
    branches: [ master ]
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip cryptography
        pip install wheel numpy Cython
        pip install biom-format
        pip install sphinx nbsphinx jupyter-sphinx-theme
        pip install -e .
    - name: Build docs
      run: |
        cd docs && make html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
